### ISSUE TITLE
Multitenanted use cases

### ISSUE THREAD

**Issue by jbcden** [breakroom/snap#16]
Hello, I am working on an application where we work with different companies whose data is stored in their own elasticsearch instances. Currently, we roughly have a custom solution to make queries etc as our use cases until now have been quite basic. We are hoping to do more with elasticsearch and are hoping to use a more robust solution. Looking at the docs for this project, it looks like it would work well for a single tenant but I was wondering if you have any advice on how to use this in a multitenanted application.

**Comment by tomtaylor** [comment]
We're not using it in a multi tenanted application I'm afraid. But I'd welcome suggestions on how to improve Snap to support this.
