### ISSUE TITLE
Additional info on Snap.Hit

### ISSUE THREAD

**Issue by hauptbenutzer** [breakroom/snap#3]
First, let me thank you for putting this library together, it's been working great for us!

Recently we had the need to access the `matched_queries` key in the returned Elasticsearch documents (exposing to our users which criteria had yielded the result). Because of the way the results are wrapped in the Snap.Hit struct, our only option was to [fork your repo and extend the struct](https://github.com/hauptbenutzer/snap/commit/f6ceaf3d3f30a3b42641f4e651ef2a823894a046). While this solves our immediate need, I do think it's a more general problem. I imagine having access to the `highlight` key is another common use case. 

Do you have any suggestion on how to proceed with this? We'd be happy to work on it and provide a PR.

Cheers

**Comment by tomtaylor** [comment]
Hey there, glad you're finding it useful. I think there's a couple of possible approaches here. 

- We could extend `Snap.Hit` with all the various properties that could be present. I couldn't see a definition of the full schema in the Elasticsearch docs, so we might need to just add them as we go.

- Or we accept that the schema is highly dynamic and push everything else into an `extras` key, or similar.

(Of course, it's always possible to just use `Snap.request` and bypass the niceties of the parsed structs.)

What are your thoughts?

**Comment by hauptbenutzer** [comment]
I think both options are workable, but as things currently are, I'd prefer the second one. We've already departed from the original hit's structure by renaming some of the keys (`source` vs `_source`) so I don't think it's much of a stretch to add an extras key. 

While considering this, something a little more radical came to mind: Why not get rid of the `Snap.Hit` struct altogether and instead return the raw elasticsearch hit? Besides the atom key access, there's no implemented protocols (unlike the other structs in Snap). I realise that's a whole different conversation and possibly a breaking change :-D

For now I'd go with your suggestion and start working on a corresponding PR.

**Comment by tomtaylor** [comment]
Thanks - going to close this now #4 has been merged, but feel free to reopen if there's other fields you want to add.
