### ISSUE TITLE
doc_as_upsert in bulk actions

### ISSUE THREAD

**Issue by cigrainger** [breakroom/snap#70]
Hey there! Thanks for an excellent library. I was wondering if you could point me to how I can pass `"doc_as_upsert": true` to `Snap.Bulk.Action.Update`. This line in the docs is ambiguous to me: 

> Any other options, such as pipeline: "foo" are passed through as query parameters to the [Bulk API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) endpoint. 

Is that how I should do it?

**Comment by tomtaylor** [comment]
Hi @cigrainger, sorry for the slow reply. I don't think that will do what you want, as those options are passed to the Bulk API endpoint, which means they're added to the HTTP request as query parameters, [like so](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#docs-bulk-api-query-params), not added to the element in the request body.

I think you probably want to add `doc_as_upsert` as a property on `Snap.Bulk.Action.Update`: https://github.com/breakroom/snap/blob/main/lib/snap/bulk/action.ex#L45-L58. Looking at the ElasticSearch/OpenSearch docs, it looks like there's probably a few missing properties that could be added.

**Comment by cigrainger** [comment]
Ah okay. Am I right in thinking that just needs to be added to that struct? I'll send a PR. 👍 I'll hoover up any other missing properties as well.

**Comment by NicolayD** [comment]
Chiming in to say this would be a welcome update.

**Comment by tomtaylor** [comment]
Closed by #76. Thanks!
