### ISSUE TITLE
Version 0.8.1 missing from tags. 

### ISSUE THREAD

**Issue by Ivor** [breakroom/snap#71]
Looking at the changelog there are 2 entries for 0.8.0. 
The docs on hex are for version 0.8.1 and the commit messages also include "Bump to 0.8.1". 
Did something perhaps go wrong with the tagging of the latest release?

**Comment by tomtaylor** [comment]
Thanks, this should be resolved now. I've tagged 0.8.1 as exactly the same version that was pushed to Hex. They have been some commits since, but those are currently unreleased as they mostly focus on the CI workflow.
