### ISSUE TITLE
Namespaces not optional anymore?

### ISSUE THREAD

**Issue by Cikey** [breakroom/snap#86]
Hi, today i updated snap and a lot of tests broke down. 

I traced the error back to these changes here: https://github.com/breakroom/snap/commit/51ec88fa7654388ba04de6dd4ec4dbd632b3d578

I understood the documentation in way that namespaces are optional:

```
index_namespace - see [Snap.Cluster.Namespace](https://hexdocs.pm/snap/Snap.Cluster.Namespace.html) for details (defaults to nil)
```

 But these filters basically break the hotswap and cleanup calls if no namespaces are used.

**Comment by tomtaylor** [comment]
Hmm, yes, namespaces should remain optional.

**Comment by tomtaylor** [comment]
Thanks for spotting this, I'll have a proper look at it when I get a chance over the next few days.

**Comment by Cikey** [comment]
Thanks! We changed to using namespaces as we realized we already had a environment dependent prefix anyway :) So its not super urgent for us.

Sadly i have too little time to present a fix currently. But thanks a lot for you quick response and for building this lib. :)

**Comment by tomtaylor** [comment]
@Cikey could you give #87 a go and tell me if that works as you expect?

**Comment by Cikey** [comment]
Seems to work, thanks!

**Comment by dkuku** [comment]
Snap.Indexes.list also is broken without prefixes set.
I'm getting an empty list:
```
iex [13:00 :: 8] > Snap.Indexes.create(Cluster, :customers, CustomersCore.ElasticSearch.Index.customer())
iex [13:00 :: 9] > Snap.Indexes.list(Cluster)
13:01:12.976 [debug] Elasticsearch GET request path=/_cat/indices response=6ms decode=0ms total=6ms
{:ok, []}
iex [13:00 :: 10] > Snap.Indexes.list_starting_with(Cluster, "c")
13:01:40.457 [debug] Elasticsearch GET request path=/_cat/indices response=10ms decode=0ms total=10ms
{:ok, []}
iex [13:00 :: 11] > Snap.get(Cluster, "/_cat/indices", [format: "json"], [], [])
13:09:14.745 [debug] Elasticsearch GET request path=/_cat/indices response=12ms decode=0ms total=12ms
{:ok,
 [
   %{
     "dataset.size" => "249b",
     "docs.count" => "0",
     "docs.deleted" => "0",
     "health" => "yellow",
     "index" => "customers",
     "pri" => "1",
     "pri.store.size" => "249b",
     "rep" => "1",
     "status" => "open",
     "store.size" => "249b",
     "uuid" => "jjQ3p1RtQ3KfUz1ldDsthg"
   }
 ]}
