### ISSUE TITLE
Random transport errors

### ISSUE THREAD

**Issue by gabrielpra1** [breakroom/snap#9]
Hello!

I've been seeing random `%Mint.TransportError{reason: :closed}` errors when calling Elasticsearch through Snap, and usually retrying the same query works.

It looks like this is related to connection pooling, with the client keeping connections that are closed by Elasticsearch. Have you seen anything similar? Wanted to ask here before digging deeper into the issue.

**Comment by tomtaylor** [comment]
Hi @gabrielpra1 - we've been running this in production for quite a while now and not seen any issues like this. Our ES cluster is operated by Bonsai.

**Comment by gabrielpra1** [comment]
Interesting, thanks @tomtaylor! After implementing a periodic healthcheck in the API this stopped happening, so it seems this only happens after a while without requests, when the connections are probably closed.

Now, I'm still not sure if this is an Elasticsearch configuration or something we can improve in the lib. Do you have long periods without any requests?

**Comment by tomtaylor** [comment]
Have you tried setting `max_idle_time` in the Finch pool config? https://hexdocs.pm/finch/Finch.html#start_link/1-pool-configuration-options

**Comment by tomtaylor** [comment]
Closing this for now, but please reopen if you want to continue the discussion.
